# Generated by Django 5.0.4 on 2024-04-25 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('tipo', models.CharField(choices=[('Fáciles', 'Fáciles'), ('Postres', 'Postres'), ('Pollo y Carne', 'Pollo y Carne'), ('Recetas a la Parrilla', 'Recetas a la Parrilla'), ('Ensaladas', 'Ensaladas'), ('Guarniciones', 'Guarniciones'), ('Pescados y Mariscos', 'Pescados y Mariscos'), ('Recetas de Pastas', 'Recetas de Pastas'), ('Comida para Niños', 'Comida para Niños'), ('Postres para Niños', 'Postres para Niños'), ('Sopas', 'Sopas'), ('Desayunos', 'Desayunos'), ('Panes', 'Panes'), ('Salsas', 'Salsas'), ('Bebidas', 'Bebidas'), ('Platos Fuertes', 'Platos Fuertes'), ('Recetas Navideñas', 'Recetas Navideñas')], max_length=50)),
                ('pasos', models.CharField(max_length=1000)),
                ('autor', models.CharField(max_length=50)),
                ('fecha_subida', models.DateField()),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ingrediente', models.CharField(max_length=50)),
                ('cantidad', models.CharField(max_length=50)),
                ('id_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.recetas')),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.CharField(max_length=500)),
                ('id_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.recetas')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=500)),
                ('calificacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('fecha_subida', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('id_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.recetas')),
            ],
        ),
        migrations.CreateModel(
            name='ListaCompra',
            fields=[
                ('id_lista', models.AutoField(primary_key=True, serialize=False)),
                ('lista', models.CharField(max_length=1000)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usuarios')),
            ],
        ),
    ]
