# Generated by Django 5.0.4 on 2024-05-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_fotos_foto_rename_ingredientes_ingrediente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
