# Generated by Django 5.0.4 on 2024-05-08 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_contraseña_usuario_contrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre_ingrediente',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Caracteres especiales como (~!#^`'$|{}<>*) no se permiten.", regex='^[a-zA-Z]+(?:\\s[a-zA-Z]+)*$')]),
        ),
        migrations.AlterField(
            model_name='receta',
            name='autor',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Caracteres especiales como (~!#^`'$|{}<>*) no se permiten.", regex='^[a-zA-Z]+(?:\\s[a-zA-Z]+)*$')]),
        ),
        migrations.AlterField(
            model_name='receta',
            name='pasos',
            field=models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator(message="Caracteres especiales como (~!#^`'$|{}<>*) no se permiten.", regex='^[a-zA-Z]+(?:\\s[a-zA-Z]+)*$')]),
        ),
        migrations.AlterField(
            model_name='receta',
            name='titulo',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Caracteres especiales como (~!#^`'$|{}<>*) no se permiten.", regex='^[a-zA-Z]+(?:\\s[a-zA-Z]+)*$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Caracteres especiales como (~!#^`'$|{}<>*) no se permiten.", regex='^[a-zA-Z]+(?:\\s[a-zA-Z]+)*$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter valid Email address.', regex='([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\\.[A-Z|a-z]{2,})+')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Caracteres especiales como (~!#^`'$|{}<>*) no se permiten.", regex='^[a-zA-Z]+(?:\\s[a-zA-Z]+)*$')]),
        ),
    ]
