# Generated by Django 5.0.4 on 2024-05-09 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_foto_foto_alter_ingrediente_nombre_ingrediente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Email invalido tiene que tener @ y . ', regex='([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\\.[A-Z|a-z]{2,})+')]),
        ),
    ]
