# Generated by Django 5.0.4 on 2024-05-13 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_usuario_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apodo',
            field=models.CharField(default='apodo', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="Caracteres especiales como (~!#^`'$|{}<>*) no se permiten.", regex='^[a-zA-Z]+(?:\\s[a-zA-Z]+)*$')]),
        ),
    ]
