# Generated by Django 5.0.4 on 2024-05-14 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0007_usuario_apodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$Ale5AHYM7ov5dQowBafgOK$7cSmwSi0T73M/dUNfw7mLK79ZQsolJVJA1tdF5BIfQU=', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tipo',
            field=models.CharField(choices=[('Fáciles', 'Fáciles'), ('Postres', 'Postres'), ('Pollo y Carne', 'Pollo y Carne'), ('Recetas a la Parrilla', 'Recetas a la Parrilla'), ('Ensaladas', 'Ensaladas'), ('Guarniciones', 'Guarniciones'), ('Pescados y Mariscos', 'Pescados y Mariscos'), ('Recetas de Pastas', 'Recetas de Pastas'), ('Comida para Niños', 'Comida para Niños'), ('Postres para Niños', 'Postres para Niños'), ('Sopas', 'Sopas'), ('Desayunos', 'Desayunos'), ('Panes', 'Panes'), ('Salsas', 'Salsas'), ('Bebidas', 'Bebidas'), ('Platos Fuertes', 'Platos Fuertes')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apodo',
            field=models.CharField(default='apodo', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default='pbkdf2_sha256$720000$Ale5AHYM7ov5dQowBafgOK$7cSmwSi0T73M/dUNfw7mLK79ZQsolJVJA1tdF5BIfQU=', max_length=500),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
