# Generated by Django 5.0.4 on 2024-05-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_usuario_groups_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='usuario',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
