# Generated by Django 5.0.4 on 2024-05-15 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_admin_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='id_receta',
        ),
        migrations.CreateModel(
            name='IngredienteReceta',
            fields=[
                ('id_ingrediente_receta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.CharField(max_length=50)),
                ('id_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ingrediente')),
                ('id_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.receta')),
            ],
        ),
    ]
