# Generated by Django 5.0.4 on 2024-05-22 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_usuario_contrasena_alter_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='pasos',
            field=models.CharField(max_length=10000, validators=[django.core.validators.RegexValidator(message="Caracteres especiales como (~!#^`'$|{}<>*) no se permiten.", regex='^[a-zA-Z]+(?:\\s[a-zA-Z]+)*$')]),
        ),
    ]
