# Generated by Django 5.0.4 on 2024-05-22 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_receta_pasos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='descripcion',
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='receta',
            name='pasos',
            field=models.CharField(max_length=50000, validators=[django.core.validators.RegexValidator(message="Caracteres especiales como (~!#^`'$|{}<>*) no se permiten.", regex='^[a-zA-Z]+(?:\\s[a-zA-Z]+)*$')]),
        ),
    ]
