# Generated by Django 5.0.4 on 2024-05-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_receta_descripcion_alter_receta_pasos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
