# Generated by Django 5.0.4 on 2024-05-23 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_delete_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.CharField(max_length=5000),
        ),
    ]
