# Generated by Django 5.0.4 on 2024-05-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_comentario_id_usuario_alter_comentario_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
