# Generated by Django 5.0.4 on 2024-05-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_comentario_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='calificacion',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True),
        ),
    ]
