# Generated by Django 5.0.4 on 2024-05-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_receta_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='fecha_subida',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
