# Generated by Django 5.0.4 on 2024-05-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_receta_fecha_subida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='tipo',
            field=models.CharField(choices=[('Postres', 'Postres'), ('Pollo y Carne', 'Pollo y Carne'), ('Recetas a la Parrilla', 'Recetas a la Parrilla'), ('Ensaladas', 'Ensaladas'), ('Guarniciones', 'Guarniciones'), ('Pescados y Mariscos', 'Pescados y Mariscos'), ('Recetas de Pastas', 'Recetas de Pastas'), ('Sopas', 'Sopas'), ('Desayunos', 'Desayunos'), ('Panes', 'Panes'), ('Salsas', 'Salsas'), ('Bebidas', 'Bebidas')], max_length=50),
        ),
    ]
