# Generated by Django 5.0.4 on 2024-05-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_receta_pasos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
